-- Adminer 4.8.1 MySQL 8.0.29 dump

SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

SET NAMES utf8mb4;

DROP TABLE IF EXISTS `Recipes`;
CREATE TABLE `Recipes` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `author` varchar(255) NOT NULL,
  `prep` varchar(15) NOT NULL,
  `cook` varchar(15) NOT NULL,
  `serves` int NOT NULL,
  `ratings` int NOT NULL,
  `foodType` varchar(100) NOT NULL,
  `difficulty` varchar(20) NOT NULL,
  `description` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `ingredients` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `kcal` int NOT NULL,
  `fat` float NOT NULL,
  `saturates` float NOT NULL,
  `carbs` float NOT NULL,
  `sugars` float NOT NULL,
  `fibre` float NOT NULL,
  `protein` float NOT NULL,
  `salt` float NOT NULL,
  `method` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `Recipes` (`id`, `name`, `author`, `prep`, `cook`, `serves`, `ratings`, `foodType`, `difficulty`, `description`, `ingredients`, `kcal`, `fat`, `saturates`, `carbs`, `sugars`, `fibre`, `protein`, `salt`, `method`) VALUES
(1,	'Double cheese & spring vegetable tart',	'Barney Desmazery',	'30 mins',	'60 mins',	8,	13,	'Vegetarian',	'Easy',	'This savoury make-ahead tart has a delicious crumbly base – no one will realise its shop-bought pastry! Fill with goats cheese and beautiful spring veg including asparagus and fresh peas',	'500g block shortcrust pastry\r\nplain flour , for dusting\r\n25g mature cheddar , finely grated\r\n200g asparagus spears , woody ends trimmed\r\n100g fresh podded or frozen peas\r\n2 eggs\r\n100g crème fraîche\r\n150g double cream\r\nwhole nutmeg , for grating\r\n100g watercress\r\n300g or 2 logs of soft, rindless goat’s cheese',	755,	63,	35,	26,	3,	3,	18,	1.1,	'Roll the pastry out into a rectangle on a work surface lightly dusted with flour. Scatter over the cheese, fold the pastry in half and roll out again into a circle that fits a 25cm tart tin with an overhang. Chill for 20 mins. Meanwhile, cook the asparagus in boiling water for 3 mins, then drain and refresh under cold water. Cook the fresh peas the same way for a minute, or simply defrost the frozen peas.\r\nHeat oven to 200C/180C fan/gas 6. Prick the base of the tart well with a fork, line with baking parchment and fill with baking beans. Bake the tart for 30 mins, remove the parchment and beans, prick again if it has puffed up, then bake for another 10-15 mins until biscuit brown.\r\nMeanwhile, beat the eggs in a bowl, add the crème fraîche and cream, season and add a pinch of freshly grated nutmeg. Scatter the peas and most of the watercress over the tart and crumble over half the goat’s cheese. Pour over the creamy egg mixture, then lay the asparagus spears on top. Finally, slice the remaining goat’s cheese and arrange on top, then bake for 25-30 mins until the custard is just set and the cheese is golden brown. Leave to cool in the tin, trim the edges of the pastry, then remove from the tin, scatter with the remaining watercress and serve cut into slices. Can be made up to a day ahead, leave out the fridge to keep the pastry crisp.\r\n'),
(2,	'One-pot chicken chasseur',	'James Martin',	'20 mins',	'90 mins',	4,	511,	'Meat',	'Easy',	'This French bistro classic is easy to make at home and fabulous with creamy mash or crusty bread',	'1kg silverside or topside of beef with no added fat\r\n2 tbsp olive oil\r\n8 young carrots, tops trimmed (but leave a little, if you like)\r\n1 celery stick, finely chopped\r\n200ml white wine\r\n600ml rich beef stock\r\n2 bay leaves\r\n500g onion\r\na few thyme sprigs\r\n1 tsp butter\r\n1 tsp light brown or light muscovado sugar\r\n2 tsp plain flour',	487,	17,	5,	19,	15,	5,	6,	1,	'Heat 1 tsp olive oil and half of the 25g butter in a large lidded casserole.\r\nSeason 4 chicken legs, then fry for about 5 mins on each side until golden brown. Remove and set aside.\r\nMelt the remaining butter in the pan. Add 1 chopped onion, then fry for about 5 mins until soft.\r\nAdd 2 crushed garlic cloves, cook for about 1 min, add 200g small button or chestnut mushrooms, cook for 2 mins, then add 225ml red wine.\r\nStir in 2 tbsp tomato purée, let the liquid bubble and reduce for about 5 mins, then stir in 2 thyme sprigs and pour over 500ml chicken stock.\r\nSlip the chicken legs back into the pan, then cover and simmer on a low heat for about 1 hr until the chicken is very tender.\r\nRemove the chicken legs from the pan and keep warm. Rapidly boil down the sauce for 10 mins or so until it is syrupy and the flavour has concentrated.\r\nPut the chicken legs back into the sauce and serve.'),
(6,	'Pot-roast beef with French onion gravy',	'Jane Hornby',	'15 mins',	'135 mins',	4,	148,	'Meat',	'Easy',	'Silverside and topside are cheaper and leaner cuts of meat, well-suited to slow-cooking. The stock and juices make a great sauce when combined with caramelised onions',	'1 tsp olive oil\r\n25g butter\r\n4 chicken legs\r\n1 onion, chopped\r\n2 garlic cloves, crushed\r\n200g pack small button or chestnut mushrooms\r\n225ml red wine\r\n2 tbsp tomato purée\r\n2 thyme sprigs\r\n500ml chicken stock',	439,	28,	10,	7,	6,	2,	35,	1.11,	'Heat oven to 160C/140C fan/gas 3. Rub the meat with 1 tsp of the oil and plenty of seasoning. Heat a large flameproof casserole dish and brown the meat all over for about 10 mins. Meanwhile, add 2 tsp oil to a frying pan and fry the carrots and celery for 10 mins until turning golden.\r\nLift the beef onto a plate, splash the wine into the hot casserole and boil for 2 mins. Pour in the stock, return the beef, then tuck in the carrots, celery and bay leaves, trying not to submerge the carrots too much. Cover and cook in the oven for 2 hrs. (I like to turn the beef halfway through cooking.)\r\nMeanwhile, thinly slice the onions. Heat 1 tbsp oil in a pan and stir in the onions, thyme and some seasoning. Cover and cook gently for 20 mins until the onions are softened but not coloured. Remove the lid, turn up the heat, add the butter and sugar, then let the onions caramelise to a dark golden brown, stirring often. Remove the thyme sprigs, then set aside.\r\nWhen the beef is ready, it will be tender and easy to pull apart at the edges. Remove it from the casserole and snip off the strings. Reheat the onion pan, stir in the flour and cook for 1 min. Whisk the floury onions into the beefy juices in the casserole, to make a thick onion gravy. Taste for seasoning. Add the beef and carrots back to the casserole, or slice the beef and bring to the table on a platter, with the carrots to the side and the gravy spooned over.'),
(7,	'dummy',	'dummy',	'20 mins',	'20mins',	4,	100,	'veg',	'meat',	'dummy',	'dummy',	530,	3,	4,	5,	6,	7,	8,	9,	'dummy'),
(8,	'dummy dummy',	'dummy',	'20 mins',	'10 mins',	5,	420,	'veg',	'easy',	'desc',	'dummy',	500,	1,	2,	3,	4,	5,	6,	7,	'dummy'),
(11,	'Dauphinoise potatoes',	'Paul Merrett',	'20 mins',	'45 mins',	8,	261,	'Vegetarian',	'Easy',	'Thin slices of potato slow cooked in the oven with cream and garlic – the most decadent of side dishes',	'500ml double cream\r\n500ml milk\r\n3 garlic cloves\r\n8 large King Edward or Maris Piper potatoes\r\n100g grated gruyère cheese (optional)',	541,	39,	22,	39,	5,	3,	11,	0.35,	'Heat oven to 190C/170C fan/gas 5.\r\nTip 500ml double cream, 500ml milk and 3 garlic cloves into a large saucepan and bring to a simmer.\r\nSlice 8 large potatoes very finely, about 3-4mm, add them to the cream and simmer for 3 mins until just cooked.\r\nGently stir to separate the potato and stop it sinking and catching on the bottom of the pan.\r\nRemove the potatoes with a slotted spoon and place in a wide shallow ovenproof dish so that they are about 5cm in depth.\r\nPour over the garlic infused cream (discarding the garlic) – just enough to seep through the layers and leave a little moisture on the surface.\r\nScatter over 100g grated gruyère cheese, if using, then bake for 30 mins until the potatoes are soft and browned – increase the heat for 5 mins if not brown enough.'),
(13,	'Creamy egg curry',	'Good Food team',	'10 mins',	'20 mins',	4,	38,	'Vegatarian',	'Easy',	'It may seem like an unusual combination but this is delicious. Why not try it and see.',	'2 tbsp sunflower oil\r\n2 onions , thinly sliced\r\n2 heaped tbsp curry paste (we used Pataks Tikka Masala)\r\n400g can chopped tomato\r\n8 eggs\r\n140g frozen pea\r\n4 tbsp Greek yogurt\r\nrice and mango chutney to serve',	336,	24,	5,	11,	7,	3,	20,	1.02,	'Heat the oil in a pan, then fry the onions over a low heat for 10 mins until golden. Add the curry paste and sizzle for 2 mins, stirring. Add the tomatoes and 200ml water, season to taste, then bring to the boil. Simmer for 10 mins until you have a rich sauce.\r\nMeanwhile, boil the eggs for 8 mins, cool in cold water, then peel and halve. 3 Stir the peas and yogurt into the curry and simmer for another 2-3 mins. Put the eggs into the pan, spoon the curry sauce over and leave for another 2 mins to heat through. Serve with rice and mango chutney.'),
(14,	'Roast cauliflower with caper dressing',	'Tom Kerridge',	'20 mins',	'40 mins',	6,	6,	'Vegetarian',	'Easy',	'Cooking cauliflower this way gives it a richness that\'s balanced by the dressing. A great side dish for a roast dinner and it also works as a vegetarian main',	'1 medium cauliflower , leaves trimmed and reserved\r\n50g butter , softened\r\n1 tbsp olive oil\r\n4 tbsp capers\r\n2 tbsp chopped parsley\r\n1 lemon , zested and juiced',	112,	9,	5,	4,	3,	2,	2,	0.7,	'Heat oven to 190C/170C fan/gas 5. Scatter the cauliflower leaves into a small roasting tin, then sit the cauliflower in the middle. Rub over the butter, sprinkle with some salt and roast for 20 mins.\r\nReduce the temperature to 160C/140C/gas 3 and cook the cauliflower for 20 mins more, basting with butter. Add the oil, capers, parsley and lemon zest and juice to the hot butter and spoon over the cauliflower a few times before serving – it will soak up the dressing flavour. When you’re ready to serve, cut into wedges and serve with the crisp leaves.'),
(15,	'Spinach & ricotta pancake bake',	'Cassie Best',	'10 mins',	'35 mins',	4,	12,	'Vegetarian',	'Easy',	'Make pancakes on Shrove Tuesday and serve our spinach and ricotta pancake bake for dinner. For dessert, choose one of our sweet pancake recipes',	'1 tbsp olive oil , plus a drizzle\r\n3 garlic cloves , crushed\r\n400g can chopped tomatoes\r\n200g bag baby spinach\r\n250g tub ricotta\r\ngrating of nutmeg\r\n4 large pancakes or crêpes (see recipe, below)\r\n225g ball mozzarella , drained and torn into small pieces\r\n50g parmesan or vegetarian alternative, grated',	513,	32,	17,	25,	8,	2,	30,	1.1,	'Heat the oil in a pan, add 2 garlic cloves and sizzle for a few seconds, then tip in the tomatoes. Season, and bubble for 10-15 mins until reduced to a thick sauce. Microwave the spinach for 2 mins to wilt, or by tipping into a colander and pouring over a kettle full of hot water. When cool enough to handle, squeeze out as much liquid as you can, then roughly chop.\r\nHeat the oven to 220C/200C fan/gas 7. Mix together the ricotta, spinach, a generous grating of nutmeg, the remaining crushed garlic and some salt and pepper. Spread the tomato sauce over the base of a shallow baking dish about 20cm x 30cm. Divide the spinach mixture between the pancakes, spreading it over half the surface. Fold each pancake in half, then in half again to make a triangle. Lay the pancakes on top of the sauce, scatter with the mozzarella and parmesan. Drizzle with a little more oil and bake for 15-20 mins until bubbling.'),
(16,	'Pasta with salmon & peas',	'Caroline Hire Food writer',	'15 mins',	'12 mins',	4,	258,	'Fish',	'Easy',	'Make this salmon pasta in under 20 minutes for a dinner the whole family can enjoy. Kids will love the fun-shaped pasta while packing in fibre and omega-3',	'240g wholewheat fusilli\r\nknob of butter\r\n1 large shallot, finely chopped\r\n140g frozen peas\r\n2 skinless salmon fillets, cut into chunks\r\n140g low-fat crème fraiche\r\n1/2 low-salt vegetable stock cube\",\r\nsmall bunch of chives, snipped',	463,	19,	6,	44,	5,	7,	25,	0.2,	'Bring a pan of water to the boil and cook the fusilli according to the pack instructions.\r\nMeanwhile, heat a knob of butter in a saucepan, then add the shallot and cook for 5 mins or until softened.\r\nAdd the peas, salmon, creme fraîche and 50ml water. Crumble in the stock cube.\r\nCook for 3-4 mins until cooked through, stir in the chives and some black pepper. Then stir through to coat the pasta. Serve in bowls.')
ON DUPLICATE KEY UPDATE `id` = VALUES(`id`), `name` = VALUES(`name`), `author` = VALUES(`author`), `prep` = VALUES(`prep`), `cook` = VALUES(`cook`), `serves` = VALUES(`serves`), `ratings` = VALUES(`ratings`), `foodType` = VALUES(`foodType`), `difficulty` = VALUES(`difficulty`), `description` = VALUES(`description`), `ingredients` = VALUES(`ingredients`), `kcal` = VALUES(`kcal`), `fat` = VALUES(`fat`), `saturates` = VALUES(`saturates`), `carbs` = VALUES(`carbs`), `sugars` = VALUES(`sugars`), `fibre` = VALUES(`fibre`), `protein` = VALUES(`protein`), `salt` = VALUES(`salt`), `method` = VALUES(`method`);

DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `user_id` int NOT NULL AUTO_INCREMENT,
  `username` varchar(15) NOT NULL,
  `email` varchar(40) NOT NULL,
  `password` varchar(255) NOT NULL,
  PRIMARY KEY (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=COMPACT;

INSERT INTO `users` (`user_id`, `username`, `email`, `password`) VALUES
(4,	'admin',	'admin@gmail.com',	'admin1234'),
(5,	'maithri',	'maithri@gmail.com',	'maithri1234'),
(6,	'harika',	'harika@gmail.com',	'harika')
ON DUPLICATE KEY UPDATE `user_id` = VALUES(`user_id`), `username` = VALUES(`username`), `email` = VALUES(`email`), `password` = VALUES(`password`);

-- 2022-05-11 19:38:42
